# Generated by Django 3.1.4 on 2020-12-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20201208_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='optional',
        ),
    ]
